### ISSUE TITLE
tiny problems

### ISSUE THREAD

**Issue by daimajia** [shell-software/fab#1]
1. Please generate a `gradlew` file by running `gradle wrapper`
2. Please include sample projects.

A really cool and useful project.

**Comment by vbaidak** [comment]
Hi
1. I thought a less of code is better. However, many of other project have actually a gradle wrapper and it seems that having it will make it easier to use in travis CI. Okay - I will add it
2. Will also add a sample project

Wait for update today - tomorrow
Have a nice day

**Comment by vbaidak** [comment]
Hi,

This will be fixed the nearest time (today - tomorrow)

**Comment by daimajia** [comment]
@shell-software  Awesome.

**Comment by vbaidak** [comment]
This is done.
Sorry for the delay.
