### ISSUE TITLE
Changing size of button

### ISSUE THREAD

**Issue by ethpran** [shell-software/fab#19]
Hi,

Great library.  The only issue I have run into is that the size of the button is seemingly not customizable beyond Normal or Mini.  Setting the height and width of the button in XML does nothing as far as I can tell. I saw from your video that this was on purpose in order to comply with Material Design guidelines, however it would be nice to be able to not have this limitation.  Would it be possible to add custom sizing?

**Comment by vbaidak** [comment]
Hi **ethpran**

**setSize(float)** public void method has been already implemented in [**branch 1.1.0**](https://github.com/shell-software/fab/tree/1.1.0), which soon will be merged with trunk and released

Check for updates

**Comment by ethpran** [comment]
very cool! great job!
