### ISSUE TITLE
Default shadow offset does conform to material design guidelines

### ISSUE THREAD

**Issue by danhawkes** [shell-software/fab#20]
The light source in material design is always directly above the element, so shadows do not ordinarily have an x offset.

http://www.google.com/design/spec/what-is-material/environment.html#environment-3d-world
http://www.google.com/design/spec/components/buttons.html#buttons-floating-action-button

Would you please consider changing the default x offset to zero, as the typical user likely just wants a button with the recommended style?

**Comment by vbaidak** [comment]
Hi **danhawkes**,

You're completely right

Yes, these values will be fixed and the shadow defaults will be the same as described in [**Material Design Guidelines**](http://www.google.com/design/spec/components/buttons.html#buttons-floating-action-button)

Also a [**responsive elevation**](http://www.google.com/design/spec/what-is-material/objects-in-3d-space.html#objects-in-3d-space-elevation) will be added by default with the option to toggle it as user [**TurKurT656**](https://github.com/TurKurT656) [_suggested_](https://github.com/shell-software/fab/issues/11)

All this stuff is currently [_under development_](https://github.com/shell-software/fab/tree/1.1.0), however it is almost completed and soon will be release (I think this weekend or the next one)

So, check for updates && have a nice day

**Comment by danhawkes** [comment]
Great, and thank you for your work on this library.

**Comment by vbaidak** [comment]
Fixed in version 1.1.0
