### ISSUE TITLE
PayPal donate link returns error

### ISSUE THREAD

**Issue by ItsHarper** [shell-software/fab#21]
Clicking on the donate button in the readme returns the following error: 

Currently PayPal accounts in Ukraine are only able to send payments. This recipient is not eligible to receive funds.

**Comment by vbaidak** [comment]
Hi **NoahAndrews**

Thanks for letting me know.
Seems that for Ukrainian users there is no chance to use PayPal for receiving payments.

I will remove the **Donation** section in the next commit.

Have a nice day

**Comment by vbaidak** [comment]
Fixed in version 1.1.0 (removed PayPal block as PayPal currently doesn't work with Ukraine)
