### ISSUE TITLE
Hiding and showing on Sections Pager

### ISSUE THREAD

**Issue by Twissall** [shell-software/fab#23]
Hi,
I have an activity which has some section pagers of fragments. I want to dynamically hide and show the actionbutton depending on the fragment. Here is my scenario.

Main Activity inflates my layout with the actionbutton view.

onCreateView method for fragment_1. 
initActionButton()

onResume method Fragment_1
boolean shown = actionButton.isShown();
        if (shown){
            actionButton.setShowAnimation(ActionButton.Animations.ROLL_TO_DOWN);
            actionButton.dismiss();
        }

 private void initActionButton() {
        actionButton = (ActionButton) getActivity().findViewById(R.id.action_button);
    }

The first time it loads, the button is NOT visible. If I swipe to other fragments and return, it crashes:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.software.shell.fab.ActionButton.isShown()' on a null object reference
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3224)

How can I resolve this? I have tried isEnabled() to the same effect.

**Comment by vbaidak** [comment]
Hi **Twisssall**,

So, the problem is in the **Action Button** initialization.
In order to make it work I need to know what library you are using (if any).
Please post the entire code of your activity, layout and fragments here or send me it to com.software.shell@gmail.com

I will try to help you

**Comment by Twissall** [comment]
Hi there. 

Thank you for such a quick response. I debugged some more and realised that I was calling dismiss() instead of hide(). Once dismissed, I could not find the actionbutton view. Thanks again!

**Comment by vbaidak** [comment]
Hi,

Great

Best wishes,
Shell Software Inc.

**Comment by vbaidak** [comment]
Issue solved
