### ISSUE TITLE
API level 11 not 9

### ISSUE THREAD

**Issue by mksmbrtsh** [shell-software/fab#26]
This field:
android:interpolator="@android:interpolator/decelerate_cubic">
in anim-v11 folders

**Comment by vbaidak** [comment]
Hi **mksmbrtsh**,

As stated in the [**Requirements**](https://github.com/shell-software/fab#requirements) block:

> The Library requires Android SDK version 9 (Gingerbread) and higher.

The corresponded animations for **SDK** lower than **11** are in the [**anim**](https://github.com/shell-software/fab/tree/master/fab/src/main/res/anim) folder.

Please check the [**Android Providing Resources**](http://developer.android.com/guide/topics/resources/providing-resources.html#AlternativeResources) topic
Please let me know if there are any issues with animations

**Comment by mksmbrtsh** [comment]
Oh, sorry. I'm set target sdk is Gingerbread and get this errors in anim-v1 folder. Now it's work! Thx you!

**Comment by vbaidak** [comment]
Great!

Have a nice day

Best wishes,
Shell Software Inc.
