### ISSUE TITLE
Icon is outside the circle

### ISSUE THREAD

**Issue by Pitel** [shell-software/fab#27]
Android 2.3 (4+ is ok), it's also visible in Android Studio's layout preview
It's caused by `fab:rippleEffect_enabled="true"`. When I set it to `false`, it's ok again.

![device-2015-05-25-154417](https://cloud.githubusercontent.com/assets/113248/7798110/ebbf44e0-02f5-11e5-8dd6-d74f7096ab93.png)

**Comment by vbaidak** [comment]
Hi **Pitel**,

Thanks for your contribution.
This issue will be fixed in version **1.1.1**

Have a nice day

**Comment by vbaidak** [comment]
Fixed in version [**1.1.0**](https://github.com/shell-software/fab/releases/tag/1.1.1)
Please check && confirm

**Comment by Pitel** [comment]
It's fixed. Thanks!
