### ISSUE TITLE
Is the way to have margin 0dp?

### ISSUE THREAD

**Issue by HormCodes** [shell-software/fab#34]
When I delete in XML this line android:layout_marginBottom="@dimen/fab_margin", some margin would be still in mu UI. Is the way to have margin of FAB 0dp?

**Comment by vbaidak** [comment]
Hello Failos,

If you have additional margins in case of setting them explicitly to 0dp, this means that you are using Shadow / Shadow responsive effect.

In this case, there is no possibility to remove it. In [this topic](https://github.com/shell-software/fab/issues/30) I explained why.

**Comment by HormCodes** [comment]
Thanks...
