### ISSUE TITLE
cant set color of button

### ISSUE THREAD

**Issue by PappBalazs** [shell-software/fab#40]
using it from code: fab.setButtonColor(R.color.myRed);
or using it form xml: fab:button_color="@color/myRed"
has no effect at all.

Also i could set image into fab only from code xml attribute didnt work

**Comment by vbaidak** [comment]
Hi PappBalazs!

Thank you for using **ActionButton** libarary

The listed features are basic ones and work correctly (you may see how they work watching the [demo video](https://www.youtube.com/watch?v=bIT_LAZoukg)).
During the last year these features were tested by many users and no issues were found. This is true as for XML, so for dynamic code

Please do the following:
1. Check you are doing things right
2. If so, please send me the XML layout file (if any) and the code, where **ActionButton** is instantiated, configured and used

**Comment by PappBalazs** [comment]
Thank you for fast respond.

Xml: http://pastebin.com/8PCBBQWe
Java: http://pastebin.com/FSGAnfUr

**Comment by vbaidak** [comment]
1. From the documentation:

``` java
// To set button color for normal state:
actionButton.setButtonColor(getResources().getColor(R.color.fab_material_lime_500));
```

That is, you passes a resource id, but **setButtonColor** expects a **resolved** color int value
2. In your [layout](http://pastebin.com/8PCBBQWe) correct the **fab** namespace. It must point to:
"http://schemas.android.com/apk/res-auto"
3. Retest the listed features after applying the corrective actions

**Comment by PappBalazs** [comment]
Thank you my friend, it is working now.

Hope i can help you too:
update getResources.getColor in your documentation, beacause it is deprecated now, use fab.setButtonColor(ContextCompat.getColor(context, R.color.myBlue));

**Comment by vbaidak** [comment]
Great!

Sure, I shall perform refactoring and fix this in the last major release 

Thank you and have a nice day
