### ISSUE TITLE
Can Drag?

### ISSUE THREAD

**Issue by luckerbai** [shell-software/fab#43]
I want drag this button, how can I do this ?

**Comment by vbaidak** [comment]
Hi **luckerbai**.

Thank you for using **ActionButton** library.

There are few ways of moving **ActionButton** depending on what you need to implement.
In general, **ActionButton** extends an Android **View** class, so it is a simple view, which supports all of the available **View** class actions.

Answering your question, using an Android [**Dragging and Scaling**](https://developer.android.com/training/gestures/scale.html) way, you can simply override **onTouchEvent(MotionEvent)** method as follows:

``` java
@Override
public boolean onTouchEvent(MotionEvent ev) {
    super.onTouchEvent(ev);
    // your code goes here
}
```

or move the **ActionButton** using any of the [_move_](https://github.com/shell-software/fab/blob/master/README.md#moving-actionbutton) methods.
