### ISSUE TITLE
onTouchEvent to handle onClickListener

### ISSUE THREAD

**Issue by samuelmgalan** [shell-software/fab#5]
Hi.

How is onTouchEvent supposed to work? I can't find the correct way to handle onClick events. I've tried setOnClickListener and setOnTouchListener without luck. And I can't cast FloatingActionButton to Button because it gives an error.

Can you provide an example? Thanks!

**Comment by vbaidak** [comment]
Hi samuelmgalan,
1. Try this one to handle **onTouchEvent** call:

``` java
@Override
    public boolean onTouchEvent(MotionEvent event) {
        super.onTouchEvent(event);
            // Your code goes here
        return true; // if handled, otherwise false
    }
```

So you just need to call **super.onTouchEvent(event)** and return **true** if your button click is handled, otherwise **false**
2. **FloatingActionButton** extends directly the **android.view.View** class, so it can't be casted to **android.widget.Button** class

**Comment by vbaidak** [comment]
Here is how it is done in sample:

Declaration inside XML:

``` xml
<com.software.shell.fab.FloatingActionButton
            android:id="@+id/fab_activity_action_button"
            style="@style/fab_action_button_style"
            android:onClick="onActionButtonClick"
            fab:type="DEFAULT"
            />
```

and then **onActionButtonClick** method in code:

``` java
public void onActionButtonClick(View v) {
        if (hideAndShowOnClickCheckBox.isChecked()) {
            actionButton.hide();
            new Handler().postDelayed(new Runnable() {
                @Override
                public void run() {
                    actionButton.show();
                }
            }, ACTION_BUTTON_SHOW_DELAY_MS);
        }
    }
```

I will provide the full demo sample a bit later today

**Comment by samuelmgalan** [comment]
Thanks for your examples.

My problem is that onTouchEvent() cannot be overriden inside a Fragment, but that's another problem.

Thanks again!

**Comment by vbaidak** [comment]
What about setting the click listener to this button? Did you manage to make it work?

**Comment by samuelmgalan** [comment]
It doesn't work. Never gets called and I think it should be, but i have no idea why not.

**Comment by vbaidak** [comment]
Could you please send me the code here:
com.software.shell@gmail.com

I'll try to help

**Comment by vbaidak** [comment]
great
