### ISSUE TITLE
Move button up and down

### ISSUE THREAD

**Issue by ghost** [shell-software/fab#9]
Would be nice if we had methods (with a parameter for height) for moving the button up (animated) when a snackbar is shown, and move it back after snackbar is dismissed.

**Comment by vbaidak** [comment]
Hi **OKA133**,

Interesting suggestion. As I understood, snackbar is a kind of a bar placed at the bottom, right?
I won't be hard to add such methods I think
Do you have any suggestions about animations?

Thanks

**Comment by ghost** [comment]
Yes, a snackbar is something new from material design. I prefer to use this [snackbar library](https://github.com/nispok/snackbar). Also see [this](http://www.google.com/design/spec/components/snackbars-toasts.html#) for official specs for snackbar and floating action button.

I don't have any specific animation in mind, but it should at least have a slide up/down.

Thanx.

**Comment by vbaidak** [comment]
Ok. Will add it

**Comment by TurKurT656** [comment]
Hi
any process on this?

**Comment by vbaidak** [comment]
In progress [here](https://github.com/shell-software/fab/tree/1.1.0)

Will be done soon

**Comment by vbaidak** [comment]
Implemented in version 1.1.0
